import base64
from pathlib import Path
import webbrowser


def _img_to_data_uri(png_path: Path) -> str:
    data = png_path.read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:image/png;base64,{b64}"


def build_html(plot1, plot2, plot3, date):
    cwd = Path.cwd()
    outdir = cwd / "html"
    outdir.mkdir(exist_ok=True)

    outpath = outdir / "ERA5_mean_anomaly_sounding_crosssection.html"

    png_dir = cwd / "tmp_png"
    p1 = png_dir / plot1
    p2 = png_dir / plot2
    p3 = png_dir / plot3

    for p in (p1, p2, p3):
        if not p.is_file():
            raise FileNotFoundError(f"Missing PNG file: {p}")

    img1 = _img_to_data_uri(p1)
    img2 = _img_to_data_uri(p2)
    img3 = _img_to_data_uri(p3)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ERA5 visualisation – {date}</title>

<style>
:root {{
  --bg: #f5f7fa;
  --card: #ffffff;
  --border: #e5e7eb;
  --text: #111827;
  --muted: #6b7280;
}}

body {{
  margin: 0;
  padding: 40px 20px;
  font-family: system-ui, -apple-system, BlinkMacSystemFont,
               "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
}}

.container {{
  max-width: 1400px;
  margin: 0 auto;
}}

header {{
  margin-bottom: 32px;
}}

h1 {{
  font-size: 1.8rem;
  font-weight: 600;
  margin: 0 0 6px 0;
}}

.subtitle {{
  color: var(--muted);
  font-size: 0.95rem;
}}

.grid {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(420px, 1fr));
  gap: 24px;
  margin-bottom: 32px;
}}

.card {{
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 14px;
  box-shadow: 0 6px 18px rgba(0, 0, 0, 0.06);
}}

.card img {{
  width: 100%;
  height: auto;
  display: block;
  border-radius: 8px;
}}

.full {{
  grid-column: 1 / -1;
}}

footer {{
  text-align: center;
  color: var(--muted);
  font-size: 0.8rem;
  margin-top: 40px;
}}
</style>
</head>

<body>
<div class="container">

<header>
  <h1>ERA5 visualisation</h1>
  <div class="subtitle">{date}</div>
</header>

<section class="grid">
  <div class="card">
    <img src="{img1}" alt="ERA5 anomaly map">
  </div>

  <div class="card">
    <img src="{img2}" alt="ERA5 sounding">
  </div>

  <div class="card full">
    <img src="{img3}" alt="ERA5 cross-section">
  </div>
</section>

<footer>
  Generated by era5vis
</footer>

</div>
</body>
</html>
"""

    outpath.write_text(html, encoding="utf-8")
    print(f"HTML saved to: {outpath}")

    webbrowser.open(outpath.resolve().as_uri())
    return str(outpath)